version: "3.6"

networks:
#  catalog-network:
#    name: catalog-network
#    external: true
  un-network:
    name: un-network
    external: true

services:


  catalog:
    image: gt/catalog:latest
    container_name: catalog
    build:
      context: ./
      dockerfile: .docker/catalog/Dockerfile
    volumes:
      - ./:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/catalog/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - catalog_db
    networks:
      - un-network

  catalog_db:
    container_name: catalog_db
    image: mysql:8
    volumes:
      - ./.docker/catalog_db/volumes/mysql:/var/lib/mysql
      - ./shared/:/shared/:rw
    environment:
      - MYSQL_ROOT_PASSWORD=cat
      - MYSQL_USER=cat
      - MYSQL_PASSWORD=cat
      - MYSQL_DATABASE=cat
      - TERM=dumb
    ports:
      - "23311:3306"
    networks:
      - un-network

  catalog_web:
    image: catalog_web:latest
    container_name: catalog_web
    build:
      context: ./
      dockerfile: .docker/catalog_web/Dockerfile
    links:
      - catalog:php_fpm
    ports:
      - "8003:80"
    environment:
      - BASEDIR=/var/www/html

    volumes:
      - ./.docker/catalog_web/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
      - ./shared:/var/shared

    networks:
      - un-network

    depends_on:
      - catalog