gt.catalog.classificator_group_new:
  path: "/classificator_groups/new"
  controller: Gt\Catalog\Controller\ClassificatorGroupsController::newAction
  methods: GET|POST

gt.catalog.classificator_group_edit:
  path: "/classificator_groups/{code}/edit"
  controller: Gt\Catalog\Controller\ClassificatorGroupsController::editAction
  methods: GET|POST

gt.catalog.classificator_groups:
  path: "/classificator_groups"
  controller: Gt\Catalog\Controller\ClassificatorGroupsController::listAction
  methods: GET