gt.catalog.customs.keywords_list:
    path: "/customs/keywords_list"
    controller: Gt\Catalog\Controller\CustomsKeywordsController::listAction
    methods: [GET, POST]

gt.catalog.customs.keywords_import_form:
    path: "/customs/keywords_import_form"
    controller: Gt\Catalog\Controller\CustomsKeywordsController::importFormAction
    methods: [GET, POST]

gt.catalog.customs.keywords_import:
    path: "/customs/keywords_import"
    controller: Gt\Catalog\Controller\CustomsKeywordsController::importAction
    methods: [GET, POST]


gt.catalog.customs.keyword_delete:
    path: "/customs/keyword_delete/{id}"
    controller: Gt\Catalog\Controller\CustomsKeywordsController::deleteAction
    methods: [GET]

gt.catalog.customs.show_assignments_prognoze:
    path: "/customs/show_assignments_prognoze"
    controller: Gt\Catalog\Controller\CustomsKeywordsController::showAssignmentPrognoze
    methods: [GET]
