gt.catalog.language_new:
    path: "/language/new"
    controller: Gt\Catalog\Controller\LanguagesController::newAction
    methods: GET|POST

gt.catalog.language_edit:
    path: "/language/edit/{code}"
    controller: Gt\Catalog\Controller\LanguagesController::editAction
    methods: GET|POST

gt.catalog.languages:
    path: "/languages"
    controller: Gt\Catalog\Controller\LanguagesController::listAction
    methods: GET