gt.catalog.rest.products:
    path: "/products/{language}"
    controller: Gt\Catalog\Rest\Controllers\ProductsRestController::getProductsAction
    methods: GET|POST

gt.catalog.rest.categories: # deprecated
    path: "/categories/{language}"
    controller: Gt\Catalog\Rest\Controllers\ProductsRestController::getCategoriesAction
    methods: GET|POST
