gt.catalog.home:
    path: "/"
    controller: Gt\Catalog\Controller\HomeController::homeAction
    methods: GET

gt.catalog.product_list:
    path: "/products"
    controller: Gt\Catalog\Controller\ProductsController::listAction
    methods: GET

gt.catalog.product_edit:
    path: "/product/edit/{sku}"
    controller: Gt\Catalog\Controller\ProductsController::editAction
    methods: [GET, POST]

gt.catalog.product_update:
    path: "/product/update/{sku}"
    controller: Gt\Catalog\Controller\ProductsController::updateAction
    methods: POST

gt.catalog.product_delete:
    path: "/product/delete/{sku}"
    controller: Gt\Catalog\Controller\ProductsController::deleteAction
    methods: DELETE

gt.catalog.product_new:
    path: "/product/new/{sku}"
    controller: Gt\Catalog\Controller\ProductsController::newAction
    methods: GET



