gt.catalog.home:
    path: "/"
    controller: Gt\Catalog\Controller\HomeController::homeAction
    methods: GET

gt.catalog.product_list:
    path: "/products"
    controller: Gt\Catalog\Controller\ProductsController::listAction
    methods: GET

gt.catalog.product_edit:
    path: "/product/edit/{sku}/l/{languageCode}"
    controller: Gt\Catalog\Controller\ProductsController::editAction
    methods: [GET, POST]

## gal nebereikalingas
gt.catalog.product_update:
    path: "/product/update/{sku}"
    controller: Gt\Catalog\Controller\ProductsController::updateAction
    methods: POST

gt.catalog.product_delete:
    path: "/product/delete/{sku}"
    controller: Gt\Catalog\Controller\ProductsController::deleteAction
    methods: DELETE

## gal nebereikalingas
gt.catalog.product_new:
    path: "/product/new/{sku}"
    controller: Gt\Catalog\Controller\ProductsController::newAction
    methods: GET


gt.catalog.product_pictures:
    path: "/product/{sku}/pictures/"
    controller: Gt\Catalog\Controller\ProductsController::picturesList
    methods: GET

gt.catalog.import_products_form:
    path: "/products/import_form"
    controller: Gt\Catalog\Controller\ProductsController::importProductsFormAction
    methods: GET

gt.catalog.import_products:
    path: "/products/import"
    controller: Gt\Catalog\Controller\ProductsController::importProductsAction
    methods: POST



gt.catalog.product_pictures_add:
    path: "/product/{sku}/pictures/add"
    controller: Gt\Catalog\Controller\ProductsController::addPictureForm
    methods: GET

