gt.catalog.home:
    path: "/"
    controller: Gt\Catalog\Controller\HomeController::homeAction
    methods: GET

gt.catalog.admin_home:
    path: "/admin"
    controller: Gt\Catalog\Controller\AdminHomeController::homeAction
    methods: GET

_gt.catalog.rest:
    resource: "rest-routing.yml"
    prefix: '/api/ezp/v2'

_gt.catalog.rest_v3:
    resource: "rest-routing-v3.yml"
    prefix: '/api/v3'
