services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


    Gt\Catalog\Controller\:
        resource: '../../Controller/*'
        tags: [ "controller.service_arguments"]

    gt.catalog.catalog_dao:
        class: 'Gt\Catalog\Dao\CatalogDao'
        public: true
        arguments:
            - '@logger'
            - '@doctrine'

    gt.catalog.language_dao:
        class: 'Gt\Catalog\Dao\LanguageDao'
        public: true
        arguments:
            - '@logger'
            - '@doctrine'

    gt.catalog.products_service:
        class: 'Gt\Catalog\Services\ProductsService'
        arguments:
            - '@logger'
            - '@gt.catalog.catalog_dao'
            - '@gt.catalog.language_dao'

    gt.catalog.languages_service:
        class: 'Gt\Catalog\Services\LanguagesService'
        arguments:
            - '@logger'
            - '@gt.catalog.language_dao'

    Gt\Catalog\Controller\ProductsController:
        tags:
            - "controller.service_arguments"
        bind:
            $logger: '@logger'
            $productsService: '@gt.catalog.products_service'

    Gt\Catalog\Controller\LanguagesController:
        tags:
            - "controller.service_arguments"
        bind:
            $logger: '@logger'
            $languagesService: '@gt.catalog.languages_service'

# ------------------  Classificator groups start -------------------------

    gt.catalog.classificator_group_dao:
        class: 'Gt\Catalog\Dao\ClassificatorGroupDao'
        public: true
        arguments:
            - '@logger'
            - '@doctrine'

    gt.catalog.classificator_dao:
        class: 'Gt\Catalog\Dao\ClassificatorDao'
        public: true
        arguments:
            - '@logger'
            - '@doctrine'

    gt.catalog.classificator_groups_service:
        class: 'Gt\Catalog\Services\ClassificatorGroupsService'
        arguments:
            - '@logger'
            - '@gt.catalog.classificator_group_dao'

    Gt\Catalog\Controller\ClassificatorGroupsController:
        tags:
            - "controller.service_arguments"
        bind:
            $logger: '@logger'
            $classificatorGroupsService: '@gt.catalog.classificator_groups_service'

# ------------------  Classificator groups end -------------------------

# ------------------  Categories start ---------------------------------

    gt.catalog.category_dao:
        class: 'Gt\Catalog\Dao\CategoryDao'
        public: true
        arguments:
            - '@logger'
            - '@doctrine'

    gt.catalog.categories_service:
        class: 'Gt\Catalog\Services\CategoriesService'
        arguments:
            - '@logger'
            - '@gt.catalog.category_dao'
            - '@gt.catalog.language_dao'

    Gt\Catalog\Controller\CategoriesController:
        tags:
            - "controller.service_arguments"
        bind:
            $logger: '@logger'
            $categoriesService: '@gt.catalog.categories_service'

# ------------------  Categories end ------------------------------------

    gt.catalog.classificators_service:
        class: 'Gt\Catalog\Services\ClassificatorsService'
        arguments:
            - '@logger'
            - '@gt.catalog.classificator_group_dao'
            - '@gt.catalog.classificator_dao'
            - '@gt.catalog.catalog_dao'
            - '@gt.catalog.language_dao'

    Gt\Catalog\Controller\ClassificatorsController:
        tags:
            - "controller.service_arguments"
        bind:
            $logger: '@logger'
            $classificatorsService: '@gt.catalog.classificators_service'
            $languagesService: '@gt.catalog.languages_service'


# -- pictures --
    Gt\Catalog\Controller\PicturesController:
        tags:
            - "controller.service_arguments"
        bind:
            $logger: '@logger'
            $picturesService: '@gt.catalog.pictures_service'
            $productsService: '@gt.catalog.products_service'

    gt.catalog.pictures_dao:
        class: 'Gt\Catalog\Dao\PicturesDao'
        public: true
        arguments:
            - '@logger'
            - '@doctrine'

    gt.catalog.pictures_service:
        class: 'Gt\Catalog\Services\PicturesService'
        arguments:
            - '@gt.catalog.pictures_dao'
        calls:
            - [setRootPath, ['%kernel.project_dir%']]
            - [setBaseDir, ['img']]

