
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


    Gt\Catalog\Controller\:
        resource: '../../Controller/*'
        tags: [ "controller.service_arguments"]

    gt.catalog.catalog_dao:
        class: 'Gt\Catalog\Dao\CatalogDao'
        public: true
        arguments:
            - '@logger'
            - '@doctrine'

    gt.catalog.language_dao:
        class: 'Gt\Catalog\Dao\LanguageDao'
        public: true
        arguments:
            - '@logger'
            - '@doctrine'

    gt.catalog.products_service:
        class: 'Gt\Catalog\Services\ProductsService'
        arguments:
            - '@logger'
            - '@gt.catalog.catalog_dao'
            - '@gt.catalog.language_dao'
            - '@gt.catalog.category_dao'
            - '@doctrine.orm.entity_manager'
            - '%gt.catalog.max_csv%'

    gt.catalog.languages_service:
        class: 'Gt\Catalog\Services\LanguagesService'
        arguments:
            - '@logger'
            - '@gt.catalog.language_dao'

    Gt\Catalog\Controller\ProductsController:
        tags:
            - "controller.service_arguments"
        arguments:
            - '@gt.catalog.services.table_service'
            - '@gt.catalog.table_data.products'
            - '@gt.catalog.guzzle'
        bind:
            $logger: '@logger'
            $productsService: '@gt.catalog.products_service'
            $categoriesService: '@gt.catalog.categories_service'
            $pdfGeneratorUrl: '%env(LABEL_PDF_GENERATOR_URL)%'
            $categoryDao: '@gt.catalog.category_dao'

    Gt\Catalog\Controller\LanguagesController:
        arguments:
            - '@gt.catalog.services.table_service'
            - '@gt.catalog.table_data.languages'
        tags:
            - "controller.service_arguments"
        bind:
            $logger: '@logger'
            $languagesService: '@gt.catalog.languages_service'

# ------------------  Classificator groups start -------------------------

    gt.catalog.classificator_group_dao:
        class: 'Gt\Catalog\Dao\ClassificatorGroupDao'
        public: true
        arguments:
            - '@logger'
            - '@doctrine'

    gt.catalog.classificator_dao:
        class: 'Gt\Catalog\Dao\ClassificatorDao'
        public: true
        arguments:
            - '@logger'
            - '@doctrine'

    gt.catalog.classificator_groups_service:
        class: 'Gt\Catalog\Services\ClassificatorGroupsService'
        arguments:
            - '@logger'
            - '@gt.catalog.classificator_group_dao'

    Gt\Catalog\Controller\ClassificatorGroupsController:
        arguments:
            - '@gt.catalog.services.table_service'
            - '@gt.catalog.table_data.classificator_groups'
        tags:
            - "controller.service_arguments"
        bind:
            $logger: '@logger'
            $classificatorGroupsService: '@gt.catalog.classificator_groups_service'

# ------------------  Classificator groups end -------------------------

# ------------------  Categories start ---------------------------------

    gt.catalog.category_dao:
        class: 'Gt\Catalog\Dao\CategoryDao'
        public: true
        arguments:
            - '@logger'
            - '@doctrine'

    gt.catalog.categories_service:
        class: 'Gt\Catalog\Services\CategoriesService'
        arguments:
            - '@logger'
            - '@gt.catalog.category_dao'
            - '@gt.catalog.language_dao'

    Gt\Catalog\Controller\CategoriesController:
        arguments:
            - '@gt.catalog.services.table_service'
            - '@gt.catalog.table_data.categories'
        tags:
            - "controller.service_arguments"
        bind:
            $logger: '@logger'
            $categoriesService: '@gt.catalog.categories_service'

# ------------------  Categories end ------------------------------------

    gt.catalog.classificators_service:
        class: 'Gt\Catalog\Services\ClassificatorsService'
        arguments:
            - '@logger'
            - '@gt.catalog.classificator_group_dao'
            - '@gt.catalog.classificator_dao'
            - '@gt.catalog.catalog_dao'
            - '@gt.catalog.language_dao'

    Gt\Catalog\Controller\ClassificatorsController:
        arguments:
            - '@gt.catalog.services.table_service'
            - '@gt.catalog.table_data.classificators'
        tags:
            - "controller.service_arguments"
        bind:
            $logger: '@logger'
            $classificatorsService: '@gt.catalog.classificators_service'
            $languagesService: '@gt.catalog.languages_service'


# -- pictures --
    Gt\Catalog\Controller\PicturesController:
        tags:
            - "controller.service_arguments"
        bind:
            $logger: '@logger'
            $picturesService: '@gt.catalog.pictures_service'
            $productsService: '@gt.catalog.products_service'

    gt.catalog.pictures_dao:
        class: 'Gt\Catalog\Dao\PicturesDao'
        public: true
        arguments:
            - '@logger'
            - '@doctrine'

    gt.catalog.pictures_service:
        class: 'Gt\Catalog\Services\PicturesService'
        arguments:
            - '@logger'
            - '@gt.catalog.pictures_dao'
        calls:
            - [setRootPath, ['%kernel.project_dir%']]
            - [setBaseDir, ['img']]

    Gt\Catalog\Transformer\ProductTransformer:
        arguments:

    # ----------------- REST -----------------------------------
    gt.catalog.products_rest_service:
        class: 'Gt\Catalog\Services\Rest\ProductsRestService'
        arguments:
            - '@logger'
            - '@gt.catalog.catalog_dao'
            - '@gt.catalog.category_dao'
#            - '@gt.catalog.categories_service'
            - '@gt.catalog.pictures_dao'
            - '@gt.catalog.pictures_service'
            - '@gt.catalog.language_dao'
            - '@Gt\Catalog\Transformer\ProductTransformer'
            - '@Gt\Catalog\Repository\PackageTypeRepository'

    Gt\Catalog\Rest\Controllers\ProductsLegacyRestController:
        tags:
            - "controller.service_arguments"
        bind:
            $logger: '@logger'
            $productsRestService: '@gt.catalog.products_rest_service'

    Gt\Catalog\Rest\Controllers\ProductsRestController:
        tags:
            - "controller.service_arguments"
        bind:
            $logger: '@logger'
            $productsRestService: '@gt.catalog.products_rest_service'
            $categoriesRestService: '@gt.catalog.categories_rest_service'
            $languageDao: '@gt.catalog.language_dao'
            $serializer: '@jms_serializer'
            $secretToken: '%env(SECRET_TOKEN)%'

    Gt\Catalog\Rest\Controllers\PackagesRestController:
        tags:
            - "controller.service_arguments"
        bind:
            $logger: '@logger'
            $tmpPackagesDao: '@gt.catalog.tmp_packages_dao'

    # ------------------ rest -------------------------------------------

    gt.catalog.guzzle:
        class: 'GuzzleHttp\Client'

    gt.catalog.katalogas_client:
        class: 'Gt\Catalog\Services\Legacy\KatalogasClient'
        arguments:
            - '@gt.catalog.guzzle'
            - 'application/vnd.ez.api.Content+json'
            - '@monolog.logger.katalogas_client'

    # ------------------ legacy -----------------------------------------
    gt.catalog.tmp_dao:
        class: 'Gt\Catalog\Services\Legacy\TmpDao'
        arguments:
            - '@logger'
            - '@doctrine'
            -
    gt.catalog.legacy_importer_service:
        class: Gt\Catalog\Services\Legacy\LegacyImporterService
        arguments:
            - '@logger'
            - '@gt.catalog.katalogas_client'
            - '@gt.catalog.tmp_dao'
            - '@gt.catalog.pictures_service'

    # ------------- commands --------------------------------------------
    gt.catalog.legacy.import_data_to_tmp_command:
        class: Gt\Catalog\Command\Legacy\ImportTmpDataFromRestCommand
        tags:
            - { name: 'console.command', command: 'catalog:import_data_to_tmp' }
        arguments:
            - '@logger'
            - '@gt.catalog.legacy_importer_service'

    gt.catalog.legacy.download_legacy_pictures_command:
        class: Gt\Catalog\Command\Legacy\DownloadLegacyPicturesCommand
        tags:
            - { name: 'console.command', command: 'catalog:download_legacy_pictures' }
        arguments:
            - '@logger'
            - '@gt.catalog.legacy_importer_service'

    # --------------- customs ----------------------------------------

    gt.catalog.customs_number_dao:
        class: 'Gt\Catalog\Dao\CustomsNumberDao'
        arguments:
            - '@logger'
            - '@doctrine'

    gt.catalog.import_customs_number_service:
        class: 'Gt\Catalog\Services\ImportCustomsNumbersService'
        arguments:
            - '@logger'
            - '@gt.catalog.customs_number_dao'

    gt.catalog.import_customs_number_command:
        class: 'Gt\Catalog\Command\ImportCustomsNumbersCommand'
        arguments:
            - '@logger'
            - '@gt.catalog.import_customs_number_service'
        tags:
            - { name: 'console.command', command: 'catalog:import_customs_numbers' }

    gt.catalog.auto_assign_customs_numbers_service:
        class: 'Gt\Catalog\Services\AutoAssignCustomsNumbersService'
        arguments:
            - '@logger'
            - '@doctrine'

    gt.catalog.auto_assign_customs_numbers_command:
        class: 'Gt\Catalog\Command\AutoAssignCustomsNumbersCommand'
        arguments:
            - '@logger'
            - '@gt.catalog.auto_assign_customs_numbers_service'
        tags:
            - { name: 'console.command', command: 'catalog:auto_assign_customs_numbers' }

    Gt\Catalog\Controller\UsersController:
        arguments:
            - '@gt.catalog.services.table_service'
            - '@gt.catalog.table_data.users'
        tags:
            - "controller.service_arguments"
        bind:
            $logger: '@logger'
            $usersService: '@gt.catalog.users_service'

    Gt\Catalog\Repository\ImportPicturesJobRepository:
        tags: [ 'doctrine.repository_service' ]

    Gt\Catalog\Controller\ImagesImportController:
        arguments:
            - '@gt.catalog.services.table_service'
            - '@gt.catalog.table_data.images_import'
        tags:
            - "controller.service_arguments"
        bind:
            $logger: '@logger'
            $importPicturesService: '@gt.catalog.import_pictures_service'
            $picturesService: '@gt.catalog.pictures_service'



    gt.catalog.test:
        class: 'Gt\Catalog\Command\TestCommand'
        arguments:
            - '@logger'
        tags:
            - { name: 'console.command', command: 'catalog:test' }

    gt.catalog.health_search_unexisting_pictures_command:
        class: 'Gt\Catalog\Command\HealthSearchUnexistingPicturesCommand'
        arguments:
            - '@logger'
            - '@gt.catalog.pictures_service'
        tags:
            - { name: 'console.command', command: 'catalog:health_search_unexisting_pictures' }

    gt.catalog.remove_duplicate_pictures_service:
        class: 'Gt\Catalog\Services\RemoveDuplicatePicturesService'
        arguments:
            - '@logger'
            - '@doctrine.orm.entity_manager'
            - '@gt.catalog.pictures_service'


    gt.catalog.remove_duplicate_pictures_command:
        class: 'Gt\Catalog\Command\RemoveDuplicatePicturesCommand'
        arguments:
            - '@logger'
            - '@gt.catalog.remove_duplicate_pictures_service'
        tags:
            - { name: 'console.command', command: 'catalog:remove_duplicate_pictures' }



    gt.catalog.remove_unassigned_pictures_service:
        class: 'Gt\Catalog\Services\RemoveUnassignedPicturesService'
        arguments:
            - '@logger'
            - '@gt.catalog.pictures_service'



    gt.catalog.remove_unassigned_pictures_command:
        class: 'Gt\Catalog\Command\RemoveUnassignedPicturesCommand'
        arguments:
            - '@logger'
            - '@gt.catalog.remove_unassigned_pictures_service'
        tags:
            - { name: 'console.command', command: 'catalog:remove_unassigned_pictures' }



    Gt\Catalog\Controller\BrandsController:
        arguments:
            - '@gt.catalog.services.table_service'
            - '@gt.catalog.table_data.brands'
        tags:
            - "controller.service_arguments"
        bind:
            $brandsService: '@gt.catalog.brands_service'

    gt.catalog.categories_rest_service:
        class: 'Gt\Catalog\Services\Rest\CategoriesRestService'
        arguments:
            - '@logger'
            - '@gt.catalog.categories_service'
            - '@gt.catalog.language_dao'

    gt.catalog.auto_assign_customs_numbers_by_keywords_service:
        class: 'Gt\Catalog\Services\AutoAssignCustomsNumbersByKeywordsService'
        arguments:
            - '@logger'
            - '@gt.catalog.customs.keywords_service'
        calls:
            - [setLanguages,[['en','lt']]]

    Gt\Catalog\Controller\CustomsKeywordsController:
        tags:
            - "controller.service_arguments"
        bind:
            $customsKeywordsService: '@gt.catalog.customs.keywords_service'
            $autoAssignCustomsNumbersByKeywordsService: '@gt.catalog.auto_assign_customs_numbers_by_keywords_service'

    gt.catalog.auto_assign_customs_numbers_by_keywords_command:
        class: 'Gt\Catalog\Command\AutoAssignCustomsNumbersByKeywordsCommand'
        arguments:
            - '@logger'
            - '@gt.catalog.auto_assign_customs_numbers_by_keywords_service'
        tags:
            - { name: 'console.command', command: 'catalog:auto_assign_customs_numbers_by_keywords' }


    gt.catalog.tmp_packages_dao:
        class: 'Gt\Catalog\Dao\TmpPackagesDao'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@jms_serializer'

    gt.catalog.services.table_service:
        class: 'Gt\Catalog\Services\TableService'
        arguments:
            - '@twig'

    gt.catalog.table_data.brands:
        class: 'Gt\Catalog\TableData\BrandsTableData'

    gt.catalog.table_data.categories:
        class: 'Gt\Catalog\TableData\CategoriesTableData'

    gt.catalog.table_data.classificators:
        class: 'Gt\Catalog\TableData\ClassificatorsTableData'

    gt.catalog.table_data.classificator_groups:
        class: 'Gt\Catalog\TableData\ClassificatorGroupsTableData'

    gt.catalog.table_data.languages:
        class: 'Gt\Catalog\TableData\LanguagesTableData'

    gt.catalog.table_data.images_import:
        class: 'Gt\Catalog\TableData\ImagesImportTableData'

    gt.catalog.table_data.products:
        class: 'Gt\Catalog\TableData\ProductsTableData'

    gt.catalog.table_data.users:
        class: 'Gt\Catalog\TableData\UsersTableData'


    Gt\Catalog\Repository\PackageTypeRepository:
        tags: [ 'doctrine.repository_service' ]

