services:
    gt.catalog.products_controller:
        public: true
        #tags: [controller.service_arguments]
        class: 'Gt\Catalog\Controller\ProductsController'
        arguments:
            - '@logger'
            - '@twig'