<?php
/**
 * Created by PhpStorm.
 * User: giedrius
 * Date: 20.7.17
 * Time: 20.25
 */

namespace Gt\Catalog\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class PictureFormType  extends AbstractType
{
    private $picture;

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
//        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    }

}