monolog:
    channels:
        - 'katalogas_client'

    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        katalogas_client:
            type: stream
            level: debug
            channels: katalogas_client
            path: '%kernel.logs_dir%/katalogas_client.log'
