#index:
#    path: /
#    controller: App\Controller\DefaultController::index


catalog_routes:
    resource: '@CatalogBundle/Resources/config/routes.yml'

languages_routes:
    resource: '@CatalogBundle/Resources/config/languages_routes.yml'

classificator_groups_routes:
    resource: '@CatalogBundle/Resources/config/classificator_groups_routes.yml'
