services:
    gt.catalog.import_pictures_service:
        class: 'Gt\Catalog\Services\ImportPicturesService'
        arguments:
            - '@logger'
            - '@doctrine.orm.entity_manager'
            - '%kernel.project_dir%/jobs'
            - '@gt.catalog.pictures_service'
            - '@gt.catalog.catalog_dao'

    gt.catalog.process_pictures_import_command:
        class: 'Gt\Catalog\Command\ProcessPicturesImportCommand'
        arguments:
            - '@logger'
            - '@gt.catalog.import_pictures_service'
        tags:
            - { name: 'console.command', command: 'catalog:process_pictures_import_jobs' }

