services:
  gt.catalog.product_log_service:
    class: 'Gt\Catalog\Services\ProductLogService'
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@Symfony\Component\Security\Core\Security'
